// This is a Javascript test harness that simulates the execution of Lambda function code
// From the command prompt, type "node test.js"

var MyLambdaFunction = require('../index.js'); // assumes single Lambda function with exports.handler
var secrets = require('../secrets.json');

// this is the Lambda request data, generated by the Alexa service.  Replace with your actual Alexa request.
var event =
    {
        "session": {
            "sessionId": secrets.sessionId,
            "application": {
                "applicationId": secrets.APP_ID
            },
            "attributes": {},
            "user": {
                "userId": secrets.userId
            },
            "new": true
        },
        "request": {
            "type": "IntentRequest",
            "requestId": secrets.requestId,
            "locale": "de-DE",
            "timestamp": "2017-07-19T12:53:19Z",
            "intent": {
                "name": "ConvertUnitIntent",
                "slots": {
                    "fromunit": {
                        "name": "fromunit",
                        "value": "meter",
                        "resolutions": {
                            "resolutionsPerAuthority": [
                                {
                                    "authority": secrets.authority,
                                    "status": {
                                        "code": "ER_SUCCESS_MATCH"
                                    },
                                    "values": [
                                        {
                                            "value": {
                                                "name": "meter",
                                                "id": "m"
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    },
                    "tounit": {
                        "name": "tounit",
                        "value": "centimeter",
                        "resolutions": {
                            "resolutionsPerAuthority": [
                                {
                                    "authority": secrets.authority,
                                    "status": {
                                        "code": "ER_SUCCESS_MATCH"
                                    },
                                    "values": [
                                        {
                                            "value": {
                                                "name": "centimeter",
                                                "id": "cm"
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    },
                    "value": {
                        "name": "value",
                        "value": "5"
                    }
                }
            }
        },
        "version": "1.0"
    };

var context = {
    'succeed': function (data) {
        console.log(JSON.stringify(data, null, '\t'));

    },
    'fail': function (err) {
        console.log('context.fail occurred');
        console.log(JSON.stringify(err, null, '\t'));
    }

};

function callback(error, data) {
    if (error) {
        console.log('error: ' + error);
    } else {
        console.log(data);
    }
}

// call the function
MyLambdaFunction['handler'](event, context, callback);